steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "source.developers.google.com/p/cloud-infra-development-001/r/gcp-cd-codelab"]
    env: ["PROJECT_ROOT=source.developers.google.com/p/cloud-infra-development-001/r/gcp-cd-codelab"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/cloud-infra-development-001/gcp-cd-codelab:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/cloud-infra-development-001/gcp-cd-codelab:$REVISION_ID"
